services:
  app:
    container_name: aaronblog-prod-app
    env_file:
      - .env.production
    networks:
      - appnet-prod

  nginx:
    container_name: aaronblog-prod-nginx
    ports:
      - "80:80"  # 生產環境使用 80 端口
    networks:
      - appnet-prod

  mysql:
    container_name: aaronblog-prod-mysql
    ports:
      - "3308:3306"  # 生產環境 MySQL 端口
    volumes:
      - mysql-prod-data:/var/lib/mysql  # 生產專用資料庫
    networks:
      - appnet-prod

networks:
  appnet-prod:
    driver: bridge 