# 生產環境配置 (AWS EC2)
# 使用方式: docker-compose -f docker-compose.prod.yml up -d
# 特色：針對 AWS EC2 優化的權限和資源配置

services:
  app:
    image: aaronlei17/aaronblog-app:latest
    container_name: aaronblog-app
    env_file:
      - .env
    # 優化的 volume 策略，減少權限衝突
    volumes:
      # 靜態文件掛載為只讀（nginx 需要存取）
      - ./public:/var/www/public:ro
      # 統一掛載整個 storage 目錄，避免部分掛載導致的權限問題
      - ./storage:/var/www/storage
      # 環境變數檔案
      - .env:/var/www/.env:ro
    # AWS EC2 環境下給 Laravel 主應用更多記憶體資源
    mem_limit: 1.2g
    mem_reservation: 600m
    restart: unless-stopped
    networks:
      - aaronblog-net
    # 暴露 PHP-FPM 端口
    expose:
      - "9000"
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: aaronblog-nginx
    ports:
      - "80:80"    # HTTP (Cloudflare 處理 HTTPS)
    volumes:
      # Nginx 配置
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # 靜態文件服務
      - ./public:/var/www/public:ro
    depends_on:
      - app
    networks:
      - aaronblog-net
    # Nginx 輕量級配置，專注靜態文件服務
    mem_limit: 128m
    mem_reservation: 64m
    restart: unless-stopped

  # Redis 快取服務
  redis:
    image: redis:7-alpine
    container_name: aaronblog-redis
    # AWS EC2 環境下大幅提升 Redis 快取性能
    mem_limit: 512m
    mem_reservation: 256m
    # 針對 AWS EC2 調整的 Redis 配置，提高快取容量
    command: redis-server --maxmemory 400mb --maxmemory-policy allkeys-lru
    expose:
      - "6379"
    networks:
      - aaronblog-net
    restart: unless-stopped

networks:
  aaronblog-net:
    driver: bridge
